# Generated by Django 3.2 on 2021-05-09 21:31

import django.core.validators
from django.db import migrations, models
import image_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Файл')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, validators=[image_service.models.validate_image_url], verbose_name='Ссылка')),
                ('image_file_resized', models.ImageField(blank=True, null=True, storage=image_service.models.OverwriteStorage(), upload_to='images/resized/', verbose_name='Файл')),
                ('width', models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)], verbose_name='Высота')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
